#!/usr/bin/env python3
"""
Brain 3D Interface System

Advanced 3D interface for loading, displaying, and interacting with anatomically
labeled brain models. This system provides a user-friendly interface to load
3D brain models generated by the Brain3DModelGenerator and visualize them
with full anatomical labeling and feature highlighting.

Key Features:
- Interactive 3D brain model loading and display
- Anatomical feature highlighting and labeling
- Real-time model manipulation and exploration
- Integration with existing neural network analysis
- Export capabilities for research and presentation
- Support for multiple brain atlases and coordinate systems
"""

import numpy as np
import plotly.graph_objects as go
import plotly.express as px
from plotly.subplots import make_subplots
import pandas as pd
from typing import Dict, List, Tuple, Optional, Any
from pathlib import Path
import json
import time
from dataclasses import dataclass

# Local imports
try:
    from brain_3d_model_generator import Brain3DModelGenerator, AnatomicalFeature, BrainTissueType
    from brain_3d_visualizer import Brain3DVisualizer
    from brain_atlas_manager import BrainAtlasManager
    HAS_DEPENDENCIES = True
except ImportError:
    HAS_DEPENDENCIES = False
    print(" Warning: Some dependencies not available - limited functionality")

@dataclass
class BrainModelInfo:
    """Information about a loaded brain model."""
    name: str
    path: str
    features_count: int
    atlas_name: str
    generation_time: float
    volume_shape: Tuple[int, int, int]
    confidence_range: Tuple[float, float]

class Brain3DInterface:
    """
    Advanced 3D interface for brain model visualization and interaction.
    """
    
    def __init__(self):
        """Initialize the Brain 3D Interface."""
        self.loaded_models = {}
        self.current_model = None
        self.visualizer = None
        self.model_generator = None
        
        if HAS_DEPENDENCIES:
            self.visualizer = Brain3DVisualizer()
            self.model_generator = Brain3DModelGenerator()
        
        print(" Brain 3D Interface System initialized")
        print("   Ready to load and visualize anatomically labeled brain models")
    
    def load_brain_model(self, model_path: str, model_name: Optional[str] = None) -> bool:
        """
        Load a 3D brain model from file.
        
        Args:
            model_path: Path to the saved brain model
            model_name: Optional name for the model
            
        Returns:
            Success status
        """
        print(f" Loading brain model from {model_path}...")
        
        if not self.model_generator:
            print(" Model generator not available")
            return False
        
        try:
            # Load the model
            success = self.model_generator.load_model(model_path)
            
            if success:
                model_name = model_name or Path(model_path).stem
                
                # Extract model information
                brain_model = self.model_generator.brain_model
                features = self.model_generator.detected_features
                
                # Create model info
                confidences = [f.confidence for f in features] if features else [0]
                model_info = BrainModelInfo(
                    name=model_name,
                    path=model_path,
                    features_count=len(features),
                    atlas_name=self.model_generator.atlas_name,
                    generation_time=brain_model['metadata'].get('generation_time', time.time()),
                    volume_shape=brain_model['shape'],
                    confidence_range=(min(confidences), max(confidences))
                )
                
                # Store the loaded model
                self.loaded_models[model_name] = {
                    'generator': self.model_generator,
                    'info': model_info,
                    'features': features,
                    'brain_model': brain_model
                }
                
                self.current_model = model_name
                
                print(f" Brain model '{model_name}' loaded successfully")
                print(f"   Features: {len(features)}")
                print(f"   Volume shape: {brain_model['shape']}")
                print(f"   Atlas: {self.model_generator.atlas_name}")
                
                return True
            
        except Exception as e:
            print(f" Error loading brain model: {e}")
        
        return False
    
    def create_brain_model_from_mri(self, mri_path: str, model_name: str, 
                                   atlas_name: str = 'harvard_oxford',
                                   max_regions: int = 200) -> bool:
        """
        Create a new brain model from MRI volume data.
        
        Args:
            mri_path: Path to MRI volume file
            model_name: Name for the new model
            atlas_name: Brain atlas to use
            max_regions: Maximum regions to detect
            
        Returns:
            Success status
        """
        print(f" Creating brain model '{model_name}' from MRI: {mri_path}...")
        
        try:
            # Create new model generator
            generator = Brain3DModelGenerator(
                atlas_name=atlas_name,
                max_regions_detect=max_regions,
                frequency_analysis=True
            )
            
            # Load and process MRI
            if generator.load_mri_volume(mri_path):
                # Detect features
                features = generator.detect_anatomical_features()
                
                # Generate 3D model
                brain_model = generator.generate_3d_model()
                
                if brain_model:
                    # Create model info
                    confidences = [f.confidence for f in features] if features else [0]
                    model_info = BrainModelInfo(
                        name=model_name,
                        path=mri_path,
                        features_count=len(features),
                        atlas_name=atlas_name,
                        generation_time=time.time(),
                        volume_shape=brain_model['shape'],
                        confidence_range=(min(confidences), max(confidences))
                    )
                    
                    # Store the model
                    self.loaded_models[model_name] = {
                        'generator': generator,
                        'info': model_info,
                        'features': features,
                        'brain_model': brain_model
                    }
                    
                    self.current_model = model_name
                    
                    print(f" Brain model '{model_name}' created successfully")
                    print(f"   Detected {len(features)} anatomical features")
                    
                    return True
            
        except Exception as e:
            print(f" Error creating brain model: {e}")
        
        return False
    
    def visualize_brain_model(self, model_name: Optional[str] = None, 
                            show_features: bool = True,
                            confidence_threshold: float = 0.5) -> Optional[go.Figure]:
        """
        Create interactive 3D visualization of a brain model.
        
        Args:
            model_name: Name of model to visualize (current if None)
            show_features: Whether to show anatomical features
            confidence_threshold: Minimum confidence for feature display
            
        Returns:
            Plotly figure object
        """
        model_name = model_name or self.current_model
        
        if not model_name or model_name not in self.loaded_models:
            print(" No brain model available for visualization")
            return None
        
        print(f" Creating 3D visualization of '{model_name}'...")
        
        model_data = self.loaded_models[model_name]
        features = model_data['features']
        brain_model = model_data['brain_model']
        
        fig = go.Figure()
        
        if show_features:
            # Filter features by confidence
            confident_features = [f for f in features if f.confidence >= confidence_threshold]
            
            if confident_features:
                # Prepare feature data
                coords = np.array([f.coordinates for f in confident_features])
                names = [f.name for f in confident_features]
                confidences = [f.confidence for f in confident_features]
                tissues = [f.properties.get('tissue_type', BrainTissueType.UNKNOWN).value for f in confident_features]
                
                # Color mapping for tissue types
                tissue_colors = {
                    'gray_matter': 'lightcoral',
                    'white_matter': 'lightblue', 
                    'cerebrospinal_fluid': 'cyan',
                    'blood_vessel': 'red',
                    'unknown': 'gray'
                }
                
                colors = [tissue_colors.get(tissue, 'gray') for tissue in tissues]
                
                # Add brain regions as scatter points
                fig.add_trace(go.Scatter3d(
                    x=coords[:, 0],
                    y=coords[:, 1],
                    z=coords[:, 2],
                    mode='markers',
                    marker=dict(
                        size=[8 + 12 * conf for conf in confidences],
                        color=colors,
                        opacity=0.8,
                        line=dict(width=1, color='white')
                    ),
                    text=[f"<b>{name}</b><br>Confidence: {conf:.3f}<br>Tissue: {tissue}<br>Coords: {coord}" 
                          for name, conf, tissue, coord in zip(names, confidences, tissues, coords)],
                    hovertemplate="%{text}<extra></extra>",
                    name="Anatomical Features"
                ))
                
                # Add connections between nearby features
                self._add_feature_connections(fig, coords, confidences, threshold=20)
        
        # Update layout
        fig.update_layout(
            title=dict(
                text=f"3D Brain Model: {model_name}<br>Features: {len([f for f in features if f.confidence >= confidence_threshold])} (confidence ≥ {confidence_threshold})",
                x=0.5
            ),
            scene=dict(
                xaxis_title='X (voxels)',
                yaxis_title='Y (voxels)',
                zaxis_title='Z (voxels)',
                bgcolor='black',
                camera=dict(
                    eye=dict(x=1.5, y=1.5, z=1.5)
                ),
                aspectmode='cube'
            ),
            width=1200,
            height=800,
            paper_bgcolor='black',
            plot_bgcolor='black',
            font=dict(color='white', size=12)
        )
        
        print(f" 3D visualization created with {len([f for f in features if f.confidence >= confidence_threshold])} features")
        return fig
    
    def _add_feature_connections(self, fig: go.Figure, coords: np.ndarray, 
                               confidences: List[float], threshold: float = 20):
        """Add connections between nearby anatomical features."""
        line_x, line_y, line_z = [], [], []
        
        for i in range(len(coords)):
            for j in range(i+1, len(coords)):
                distance = np.linalg.norm(coords[i] - coords[j])
                
                if distance < threshold:
                    # Add line between connected features
                    opacity = min(confidences[i], confidences[j])
                    
                    line_x.extend([coords[i,0], coords[j,0], None])
                    line_y.extend([coords[i,1], coords[j,1], None])
                    line_z.extend([coords[i,2], coords[j,2], None])
        
        if line_x:
            fig.add_trace(go.Scatter3d(
                x=line_x,
                y=line_y,
                z=line_z,
                mode='lines',
                line=dict(
                    color='rgba(255,255,255,0.2)',
                    width=1
                ),
                showlegend=False,
                hoverinfo='skip'
            ))
    
    def create_model_dashboard(self, model_name: Optional[str] = None) -> Optional[go.Figure]:
        """Create comprehensive dashboard for brain model analysis."""
        model_name = model_name or self.current_model
        
        if not model_name or model_name not in self.loaded_models:
            print(" No brain model available for dashboard")
            return None
        
        print(f" Creating model dashboard for '{model_name}'...")
        
        model_data = self.loaded_models[model_name]
        features = model_data['features']
        model_info = model_data['info']
        
        # Create subplots
        fig = make_subplots(
            rows=2, cols=2,
            specs=[[{'type': 'scatter3d'}, {'type': 'bar'}],
                   [{'type': 'scatter'}, {'type': 'pie'}]],
            subplot_titles=(
                '3D Brain Features',
                'Confidence Distribution',
                'Feature Detection Methods',
                'Tissue Type Distribution'
            )
        )
        
        # Panel 1: 3D Brain visualization
        if features:
            coords = np.array([f.coordinates for f in features])
            confidences = [f.confidence for f in features]
            
            fig.add_trace(
                go.Scatter3d(
                    x=coords[:, 0],
                    y=coords[:, 1],
                    z=coords[:, 2],
                    mode='markers',
                    marker=dict(
                        size=[5 + 10 * conf for conf in confidences],
                        color=confidences,
                        colorscale='Viridis',
                        showscale=True,
                        colorbar=dict(title="Confidence")
                    ),
                    name="Features"
                ),
                row=1, col=1
            )
        
        # Panel 2: Confidence distribution
        if features:
            confidence_bins = [0.5, 0.6, 0.7, 0.8, 0.9, 1.0]
            conf_counts = []
            
            for i in range(len(confidence_bins) - 1):
                count = sum(1 for f in features if confidence_bins[i] <= f.confidence < confidence_bins[i+1])
                conf_counts.append(count)
            
            fig.add_trace(
                go.Bar(
                    x=[f"{confidence_bins[i]:.1f}-{confidence_bins[i+1]:.1f}" for i in range(len(conf_counts))],
                    y=conf_counts,
                    name="Confidence Bins",
                    marker_color='skyblue'
                ),
                row=1, col=2
            )
        
        # Panel 3: Detection methods
        if features:
            methods = {}
            for feature in features:
                method = feature.properties.get('detection_method', 'unknown')
                methods[method] = methods.get(method, 0) + 1
            
            fig.add_trace(
                go.Scatter(
                    x=list(methods.keys()),
                    y=list(methods.values()),
                    mode='markers+lines',
                    marker=dict(size=10, color='orange'),
                    name="Methods"
                ),
                row=2, col=1
            )
        
        # Panel 4: Tissue types
        if features:
            tissues = {}
            for feature in features:
                tissue = feature.properties.get('tissue_type', BrainTissueType.UNKNOWN).value
                tissues[tissue] = tissues.get(tissue, 0) + 1
            
            fig.add_trace(
                go.Pie(
                    labels=list(tissues.keys()),
                    values=list(tissues.values()),
                    name="Tissue Types"
                ),
                row=2, col=2
            )
        
        # Update layout
        fig.update_layout(
            title=f"Brain Model Dashboard: {model_name}",
            height=800,
            showlegend=True,
            paper_bgcolor='black',
            plot_bgcolor='black',
            font=dict(color='white')
        )
        
        print(f" Model dashboard created for '{model_name}'")
        return fig
    
    def export_model_report(self, model_name: Optional[str] = None, 
                          output_path: Optional[str] = None) -> bool:
        """Export detailed model analysis report."""
        model_name = model_name or self.current_model
        
        if not model_name or model_name not in self.loaded_models:
            print(" No brain model available for export")
            return False
        
        output_path = output_path or f"reports/{model_name}_analysis_report.json"
        output_path = Path(output_path)
        output_path.parent.mkdir(parents=True, exist_ok=True)
        
        print(f" Exporting analysis report for '{model_name}'...")
        
        model_data = self.loaded_models[model_name]
        features = model_data['features']
        model_info = model_data['info']
        
        # Create comprehensive report
        report = {
            'model_info': {
                'name': model_info.name,
                'path': model_info.path,
                'features_count': model_info.features_count,
                'atlas_name': model_info.atlas_name,
                'generation_time': model_info.generation_time,
                'volume_shape': model_info.volume_shape,
                'confidence_range': model_info.confidence_range
            },
            'features': [
                {
                    'name': f.name,
                    'region_id': f.region_id,
                    'coordinates': f.coordinates,
                    'confidence': f.confidence,
                    'atlas_label': f.atlas_label,
                    'properties': f.properties
                }
                for f in features
            ],
            'statistics': {
                'total_features': len(features),
                'high_confidence_features': len([f for f in features if f.confidence > 0.8]),
                'tissue_distribution': {},
                'detection_method_distribution': {},
                'mean_confidence': np.mean([f.confidence for f in features]) if features else 0,
                'confidence_std': np.std([f.confidence for f in features]) if features else 0
            },
            'export_time': time.time()
        }
        
        # Calculate distributions
        for feature in features:
            tissue = feature.properties.get('tissue_type', BrainTissueType.UNKNOWN).value
            method = feature.properties.get('detection_method', 'unknown')
            
            report['statistics']['tissue_distribution'][tissue] = report['statistics']['tissue_distribution'].get(tissue, 0) + 1
            report['statistics']['detection_method_distribution'][method] = report['statistics']['detection_method_distribution'].get(method, 0) + 1
        
        # Save report
        try:
            with open(output_path, 'w') as f:
                json.dump(report, f, indent=2, default=str)
            
            print(f" Analysis report exported to {output_path}")
            return True
            
        except Exception as e:
            print(f" Error exporting report: {e}")
            return False
    
    def list_loaded_models(self) -> List[str]:
        """Get list of currently loaded model names."""
        return list(self.loaded_models.keys())
    
    def get_model_info(self, model_name: str) -> Optional[BrainModelInfo]:
        """Get information about a loaded model."""
        if model_name in self.loaded_models:
            return self.loaded_models[model_name]['info']
        return None
    
    def switch_current_model(self, model_name: str) -> bool:
        """Switch the current active model."""
        if model_name in self.loaded_models:
            self.current_model = model_name
            print(f" Switched to model '{model_name}'")
            return True
        else:
            print(f" Model '{model_name}' not found")
            return False

def main():
    """Test the Brain 3D Interface System."""
    print(" Testing Brain 3D Interface System")
    print("=" * 60)
    
    # Create interface
    interface = Brain3DInterface()
    
    # Create a test brain model from mock data
    print("\n Creating test brain model...")
    
    # Mock MRI data path (replace with real data if available)
    test_mri_path = "data/test_mri_volume.nii.gz"
    
    if not Path(test_mri_path).exists():
        print(f" Test MRI not found at {test_mri_path}")
        print("   Creating mock brain model for demonstration...")
        
        # Create a mock model using the generator directly
        if interface.model_generator:
            # Create mock volume
            mock_volume = np.random.rand(91, 109, 91)
            interface.model_generator.brain_volume = mock_volume
            
            # Preprocess and detect features
            interface.model_generator._preprocess_volume()
            features = interface.model_generator.detect_anatomical_features()
            brain_model = interface.model_generator.generate_3d_model()
            
            if brain_model:
                # Manually add to loaded models
                model_name = "Demo_Brain_Model"
                confidences = [f.confidence for f in features] if features else [0]
                model_info = BrainModelInfo(
                    name=model_name,
                    path="mock_data",
                    features_count=len(features),
                    atlas_name="harvard_oxford",
                    generation_time=time.time(),
                    volume_shape=brain_model['shape'],
                    confidence_range=(min(confidences), max(confidences))
                )
                
                interface.loaded_models[model_name] = {
                    'generator': interface.model_generator,
                    'info': model_info,
                    'features': features,
                    'brain_model': brain_model
                }
                
                interface.current_model = model_name
                print(f" Demo model created with {len(features)} features")
    else:
        # Use real MRI data
        success = interface.create_brain_model_from_mri(
            test_mri_path, 
            "Test_Brain_Model",
            max_regions=100
        )
        
        if not success:
            print(" Failed to create brain model from MRI")
            return False
    
    # Test visualization
    if interface.current_model:
        print("\n Creating 3D visualization...")
        
        # Create 3D visualization
        fig = interface.visualize_brain_model(
            confidence_threshold=0.5,
            show_features=True
        )
        
        if fig:
            print(" 3D visualization created")
            # fig.show()  # Uncomment to display
        
        # Create dashboard
        print("\n Creating model dashboard...")
        dashboard = interface.create_model_dashboard()
        
        if dashboard:
            print(" Model dashboard created")
            # dashboard.show()  # Uncomment to display
        
        # Export report
        print("\n Exporting analysis report...")
        success = interface.export_model_report()
        
        if success:
            print(" Analysis report exported")
    
    # Show summary
    print("\n" + "=" * 60)
    print("🎉 BRAIN 3D INTERFACE SYSTEM TEST COMPLETED!")
    print("=" * 60)
    
    loaded_models = interface.list_loaded_models()
    print(f"\n Interface Summary:")
    print(f"   Loaded models: {len(loaded_models)}")
    
    for model_name in loaded_models:
        info = interface.get_model_info(model_name)
        if info:
            print(f"   - {model_name}: {info.features_count} features, {info.atlas_name} atlas")
    
    return True

if __name__ == "__main__":
    main()