#!/usr/bin/env python3
"""
Bayesian Electromagnetic Field Estimation from D-LinOSS States
==============================================================

This script integrates the Bayesian estimation framework proposed by
Koide-Majima et al. (2024) into our D-LinOSS visual category investigation.

The problem:
Instead of just matching learned category templates to raw BOLD readouts,
we know D-LinOSS has ALREADY learned the temporal BOLD contrast activation
as internal electromagnetic oscillator states (the x(t) variables).

The goal:
We deduce the *original field activation* (where the cause of the BOLD
effect came from spatially) by solving the inverse problem using
Stochastic Gradient Langevin Dynamics (SGLD).

Bayesian Formulation:
    p(z | x_target) ∝ p(x_target | z) * p(z)

    - z: The underlying spatial electromagnetic field driving the voxels.
    - x_target: The observed D-LinOSS oscillator states for a given category.
    - p(x_target | z): The visual likelihood. Driven by the similarity
      between the target oscillator states and the states generated by
      feeding z through the model's learned encoding (B matrix).
    - p(z): The prior. We use our ResonanceNetwork or a regularized
      spatial prior (smoothness/sparsity) to keep z biologically plausible.

We use SGLD to sample from this posterior because it is intractable to
solve analytically. We can then project the estimated field `z` back to
the 3D brain space to see exactly WHICH voxels/regions are driving the
category perception.
"""

import os
import sys
import json
import time
import numpy as np
from collections import defaultdict

if sys.stdout.encoding and sys.stdout.encoding.lower() != 'utf-8':
    sys.stdout.reconfigure(encoding='utf-8')

sys.path.insert(0, os.path.dirname(__file__))

import torch
import torch.nn.functional as F
import nibabel as nib

from dlinoss.dlinoss_torch import DLinOSSModel, parallel_scan
from dlinoss.mri_artifact_correction import MRIHardwareConfig
from run_visual_dlinoss import (
    load_haxby_subject, build_block_labels, extract_brain_voxels
)

# ============================================================================
#  Data Preparation & Target Extraction
# ============================================================================

def preprocess_run(run_ts, TR):
    """Lightweight preprocessing: detrend + normalize."""
    N, T = run_ts.shape
    cleaned = run_ts.copy().astype(np.float32)
    t_axis = np.arange(T, dtype=np.float32)
    for i in range(N):
        coeffs = np.polyfit(t_axis, cleaned[i], 1)
        cleaned[i] -= np.polyval(coeffs, t_axis)
    mu = cleaned.mean(axis=1, keepdims=True)
    sigma = cleaned.std(axis=1, keepdims=True)
    sigma = np.where(sigma < 1e-8, 1.0, sigma)
    cleaned = (cleaned - mu) / sigma
    return np.clip(cleaned, -5.0, 5.0).T  # (T, N)


def extract_target_oscillator_states(model, x_input):
    """
    Run the D-LinOSS model and extract the internal oscillator states x(t)
    for a given input. We use the FIRST block's states as our primary target
    since it's closest to the physical voxel mapping.
    """
    model.eval()
    with torch.no_grad():
        h = model.encoder(x_input)
        block = model.blocks[0]  # Just use the first block for direct spatial mapping
        h_normed = block.norm(h)
        
        ssm = block.ssm
        L, H = h_normed.shape
        P = ssm.state_dim
        
        B_complex = torch.view_as_complex(ssm.B.contiguous())
        A, G, dt = ssm._soft_project(ssm.A_diag, ssm.G_diag, ssm.dt_raw)
        
        Bu = h_normed.to(B_complex.dtype) @ B_complex.T  # (L, P)
        
        S = 1.0 + dt * G
        M11 = 1.0 / S
        M12 = -dt * A / S
        M21 = dt / S
        M22 = 1.0 - dt.pow(2) * A / S
        
        M = torch.cat([M11, M12, M21, M22])
        M_elements = M.unsqueeze(0).repeat(L, 1)
        
        F1 = (dt / S).unsqueeze(0) * Bu
        F2 = (dt.pow(2) / S).unsqueeze(0) * Bu
        F_cat = torch.cat([F1, F2], dim=-1)
        
        _, xs_re = parallel_scan(M_elements, F_cat.real)
        _, xs_im = parallel_scan(M_elements, F_cat.imag)
        
        ys_re = xs_re[:, P:]
        ys_im = xs_im[:, P:]
        osc_states = torch.complex(ys_re, ys_im)
        
    return osc_states  # (L, P) complex


# ============================================================================
#  Bayesian Estimation via SGLD
# ============================================================================

def simulate_oscillator_states(model, z):
    """
    Simulate the oscillator states generated by a candidate field pattern `z`.
    z is shape (N_voxels,), so we treat it as a constant static activation
    over a small time window L=10 to let the oscillators react.
    """
    L = 10
    z_seq = z.unsqueeze(0).expand(L, -1)  # (L, N_voxels)
    
    h = model.encoder(z_seq)
    block = model.blocks[0]
    h_normed = block.norm(h)
    
    ssm = block.ssm
    P = ssm.state_dim
    
    B_complex = torch.view_as_complex(ssm.B.contiguous())
    A, G, dt = ssm._soft_project(ssm.A_diag, ssm.G_diag, ssm.dt_raw)
    
    Bu = h_normed.to(B_complex.dtype) @ B_complex.T
    
    S = 1.0 + dt * G
    M11 = 1.0 / S
    M12 = -dt * A / S
    M21 = dt / S
    M22 = 1.0 - dt.pow(2) * A / S
    
    M = torch.cat([M11, M12, M21, M22])
    M_elements = M.unsqueeze(0).repeat(L, 1)
    
    F1 = (dt / S).unsqueeze(0) * Bu
    F2 = (dt.pow(2) / S).unsqueeze(0) * Bu
    F_cat = torch.cat([F1, F2], dim=-1)
    
    _, xs_re = parallel_scan(M_elements, F_cat.real)
    _, xs_im = parallel_scan(M_elements, F_cat.imag)
    
    ys_re = xs_re[:, P:]
    ys_im = xs_im[:, P:]
    osc_states = torch.complex(ys_re, ys_im)
    
    # Return the average steady-state magnitude
    return torch.abs(osc_states).mean(dim=0)  # (P,)


def sgld_field_estimation(model, target_magnitudes, num_voxels, 
                          iterations=500, a=0.00015, b=0.15, gamma=0.055, T=1e-7):
    """
    Run Stochastic Gradient Langevin Dynamics (SGLD) to find the source
    electromagnetic field 'z' that caused the observed BOLD contrast.
    
    Based on Koide-Majima et al. (2024) Bayesian framework:
    z_{t+1} = z_t + (eps_t / 2) * grad(log_posterior) + noise
    """
    # Initialize the candidate field 'z' as random noise
    # We want to find the spatial cause, so z represents voxel activations
    z = torch.randn(num_voxels, requires_grad=True, dtype=torch.float32)
    
    # We want to track the best z found
    best_loss = float('inf')
    best_z = None
    
    target_mag = torch.tensor(target_magnitudes, dtype=torch.float32)
    
    for t in range(iterations):
        if z.grad is not None:
            z.grad.zero_()
            
        # 1. Forward model: What oscillator states does this field z cause?
        simulated_mag = simulate_oscillator_states(model, z)
        
        # 2. Likelihood (Visual/Field): Similarity between simulated and target
        # We use Pearson correlation as proposed by the paper, implemented as Cosine Similarity
        # on mean-centered data.
        sim_mean = simulated_mag.mean()
        tgt_mean = target_mag.mean()
        sim_c = simulated_mag - sim_mean
        tgt_c = target_mag - tgt_mean
        
        # Adding a small epsilon to denominator to prevent division by zero
        cov = torch.sum(sim_c * tgt_c)
        var_sim = torch.sqrt(torch.sum(sim_c**2) + 1e-8)
        var_tgt = torch.sqrt(torch.sum(tgt_c**2) + 1e-8)
        correlation = cov / (var_sim * var_tgt)
        
        # The paper formulation: log p(phi_hat | I) = (1/T) * Similarity
        log_likelihood = (1.0 / T) * correlation
        
        # 3. Prior p(z): We assume fields are sparse and spatially coherent.
        # We add L1 sparsity and L2 magnitude penalties.
        log_prior = -0.1 * torch.sum(torch.abs(z)) - 0.01 * torch.sum(z**2)
        
        # 4. Posterior
        log_posterior = log_likelihood + log_prior
        
        # We want to maximize posterior, so loss is -log_posterior
        loss = -log_posterior
        loss.backward()
        
        with torch.no_grad():
            # SGLD Step size schedule
            eps_t = a / ((b + t)**gamma)
            
            # Gradient step
            z += (eps_t / 2.0) * z.grad
            
            # Langevin noise injection
            noise = torch.randn_like(z) * np.sqrt(eps_t)
            z += noise
            
            # Keep track of best result
            current_loss = loss.item()
            if current_loss < best_loss:
                best_loss = current_loss
                best_z = z.clone().detach()

        if (t+1) % 100 == 0:
            print(f"      SGLD Iter {t+1:3d}: correlation = {correlation.item():.4f}, "
                  f"prior = {log_prior.item():.2f}")
            
    return best_z.numpy()


# ============================================================================
#  Main Investigation Pipeline
# ============================================================================

def run_bayesian_investigation(subject_dir, subject_name, max_voxels=500):
    """
    Train D-LinOSS, extract the electromagnetic signatures of visual categories,
    and deduce the spatial sources of those signatures using Bayesian estimation.
    """
    print(f"\n{'='*70}")
    print(f"  BAYESIAN FIELD ESTIMATION: {subject_name}")
    print(f"  Deducing spatial cause of BOLD contrast from learned dynamics")
    print(f"{'='*70}")

    # 1. Load data
    bold_runs, events_runs, TR = load_haxby_subject(subject_dir, max_runs=12)
    n_runs = len(bold_runs)
    
    # 2. Select category-sensitive voxels using between-group ANOVA
    print(f"\n  [Phase 1] Extracting brain data & selecting top {max_voxels} voxels...")
    bold_concat = np.concatenate(bold_runs, axis=-1)
    ts_2d, brain_mask, coords = extract_brain_voxels(bold_concat, percentile=20)
    
    labels_per_run = []
    categories = set()
    for events, bold in zip(events_runs, bold_runs):
        run_labels = build_block_labels(events, bold.shape[-1], TR)
        labels_per_run.append(run_labels)
        categories.update(l for l in run_labels if l != 'rest')
    categories = sorted(categories)
    all_labels_flat = [l for rl in labels_per_run for l in rl]
    
    # ANOVA F-stat
    cat_means = {}
    cat_counts = {}
    for cat in categories:
        idx = [i for i, l in enumerate(all_labels_flat) if l == cat]
        if idx:
            cat_means[cat] = ts_2d[:, idx].mean(axis=1)
            cat_counts[cat] = len(idx)
            
    grand_mean = ts_2d.mean(axis=1)
    ss_between = np.zeros(ts_2d.shape[0])
    ss_within = np.zeros(ts_2d.shape[0])
    
    for cat in categories:
        if cat in cat_means:
            ss_between += cat_counts[cat] * (cat_means[cat] - grand_mean)**2
            idx = [i for i, l in enumerate(all_labels_flat) if l == cat]
            if idx:
                ss_within += np.sum((ts_2d[:, idx] - cat_means[cat][:, None])**2, axis=1)

    k = len(cat_means)
    n_total = sum(cat_counts.values())
    f_stat = (ss_between / max(k-1, 1)) / (ss_within / max(n_total-k, 1) + 1e-10)

    top_idx = np.argsort(f_stat)[-max_voxels:]
    selected_coords = coords[top_idx]
    
    # 3. Preprocess per run
    print(f"  [Phase 2] Preprocessing and training D-LinOSS (Self-Supervised)...")
    clean_runs = []
    for bold in bold_runs:
        run_selected = bold[brain_mask][top_idx]
        cleaned = preprocess_run(run_selected, TR)
        clean_runs.append(cleaned)
        
    concat_clean = np.concatenate(clean_runs, axis=0)
    
    # 4. Train D-LinOSS model
    model = DLinOSSModel(
        input_dim=max_voxels, state_dim=32, hidden_dim=64,
        output_dim=max_voxels, num_blocks=3, drop_rate=0.0
    )
    
    x_all = torch.tensor(concat_clean, dtype=torch.float32)
    model.train()
    optimizer = torch.optim.Adam(model.parameters(), lr=1e-3)
    
    for epoch in range(100):
        optimizer.zero_grad()
        y = model(x_all)
        loss = torch.nn.functional.mse_loss(y, x_all)
        if not torch.isfinite(loss): break
        loss.backward()
        torch.nn.utils.clip_grad_norm_(model.parameters(), max_norm=1.0)
        optimizer.step()
        
    print(f"    Final Training Loss: {loss.item():.4f}")
    
    # 5. Extract target oscillator states for each category
    print(f"\n  [Phase 3] Extracting electromagnetic signatures for visual categories...")
    states = extract_target_oscillator_states(model, x_all)
    magnitudes = torch.abs(states).numpy()
    
    target_profiles = {}
    for cat in categories:
        idx = [i for i, l in enumerate(all_labels_flat) if l == cat]
        if idx:
            target_profiles[cat] = magnitudes[idx].mean(axis=0)
            
    # 6. Apply Bayesian SGLD Estimation
    print(f"\n  [Phase 4] Inferring spatial field sources via Bayesian SGLD...")
    field_estimates = {}
    
    for cat in categories:
        print(f"\n    Estimating field cause for category: {cat.upper()}")
        tgt = target_profiles[cat]
        
        # We run SGLD to find the field 'z' that maximizes the posterior probability 
        # of producing the target D-LinOSS oscillator state signature
        estimated_field = sgld_field_estimation(
            model, tgt, num_voxels=max_voxels, iterations=300
        )
        field_estimates[cat] = estimated_field
        
        # Analyze the estimated field
        top_activations = np.argsort(np.abs(estimated_field))[-5:][::-1]
        print(f"      Top highly active voxels driving this category:")
        for v in top_activations:
            crd = selected_coords[v]
            val = estimated_field[v]
            print(f"        Voxel {v:3d} at [{crd[0]:2d},{crd[1]:2d},{crd[2]:2d}]: {val:+.3f}")

    # Output to disk
    output_dir = os.path.join(os.path.dirname(__file__), '..', 
                              'dlinoss_results', f'BayesianField_{subject_name}')
    os.makedirs(output_dir, exist_ok=True)
    
    # We can save these field estimates back out to NIfTI format for viewing in a brain viewer
    print(f"\n  [Phase 5] Saving deduced fields to NIfTI volumes...")
    ref_img = nib.load(os.path.join(subject_dir, 'func', 'sub-4_task-objectviewing_run-01_bold.nii.gz'))
    affine = ref_img.affine
    shape = ref_img.shape[:3]
    
    for cat, field in field_estimates.items():
        vol = np.zeros(shape)
        for i, (f_val, crd) in enumerate(zip(field, selected_coords)):
            vol[crd[0], crd[1], crd[2]] = f_val
            
        img = nib.Nifti1Image(vol, affine)
        nib.save(img, os.path.join(output_dir, f'estimated_field_{cat}.nii.gz'))
        
    print(f"  Saved spatial field cause maps to {output_dir}")

def main():
    base = os.path.join(os.path.dirname(__file__), '..', 'data', 'openneuro', 'ds000105')
    # Because this is an intensive Bayesian simulation, we'll test on sub-4 first
    run_bayesian_investigation(os.path.join(base, 'sub-4'), 'sub-4', max_voxels=300)

if __name__ == '__main__':
    main()
