"""generate_scramble_v4_notebook.py — Chronos v4: Shared Coherent State Protocol"""
import json, pathlib

def cc(src): return {"cell_type":"code","execution_count":None,"metadata":{"id":""},"outputs":[],"source":src}
def mc(src): return {"cell_type":"markdown","metadata":{"id":""},"source":src}

cells = []

cells.append(mc([
    "# Chronos Scramble v4 — Shared Coherent State Protocol\n",
    "**Key changes from v3:**\n",
    "- **Natural frequency discovery** — find the TPU tick rate with minimum eigenvalue entropy\n",
    "- **Shared matrix initialization** — both TPUs seed from same NTP wall-clock second\n",
    "- **Gaussian phase rotation** — Alice rotates matrix column space, not size (no trivial timing change)\n",
    "- **Eigenvector alignment** as primary observable — measures shared EM coherent state\n",
    "- **25 min total** — fits in free tier quota\n",
    "\n",
    "> Cell 1: set role. Cell 3: run JAX engine. Cell 4: find natural frequency. Cell 5: dry run. Cell 6: main capture.\n",
]))

# ── Cell 1 · Config ───────────────────────────────────────────────────────────
cells.append(cc([
    "#@title 1 · Configuration { display-mode: \"form\" }\n",
    "EXPERIMENT_ROLE  = 'Alice_Scramble' #@param [\"Alice_Scramble\", \"Bob_Passive\"]\n",
    "DURATION_SECONDS = 900.0            #@param {type:\"number\"}  # 15 min\n",
    "N_STREAMS        = 4                #@param {type:\"number\"}\n",
    "CHUNK_SECONDS    = 5                #@param {type:\"number\"}\n",
    "WINDOW_PACKETS   = 32               #@param {type:\"number\"}\n",
    "SIGMA_GAUSSIAN   = 1.0              #@param {type:\"number\"}\n",
    "# lambda schedule: 2min ramp, 2min ON, 1min ramp-down, 2min OFF (7min cycle x2)\n",
    "RAMP_UP_S   = 120.0  #@param {type:\"number\"}\n",
    "ON_S        = 120.0  #@param {type:\"number\"}\n",
    "RAMP_DOWN_S =  60.0  #@param {type:\"number\"}\n",
    "OFF_S       = 120.0  #@param {type:\"number\"}\n",
    "\n",
    "import os, time, json, pathlib, shutil, threading\n",
    "import numpy as np\n",
    "\n",
    "CYCLE_S    = RAMP_UP_S + ON_S + RAMP_DOWN_S + OFF_S\n",
    "OUTPUT_DIR = f'/tmp/chronos_v4_{EXPERIMENT_ROLE.lower()}'\n",
    "pathlib.Path(OUTPUT_DIR).mkdir(parents=True, exist_ok=True)\n",
    "print(f'Role: {EXPERIMENT_ROLE}  |  Duration: {DURATION_SECONDS/60:.0f}min  |  Cycle: {CYCLE_S/60:.0f}min x {DURATION_SECONDS/CYCLE_S:.1f}')\n",
]))

# ── Cell 2 · Infrastructure Fingerprint ──────────────────────────────────────
cells.append(cc([
    "#@title 2 · Infrastructure Fingerprint\n",
    "import socket, urllib.request, json as _json\n",
    "infra = {}\n",
    "GCP_META = 'http://metadata.google.internal/computeMetadata/v1'\n",
    "def gcp_meta(path):\n",
    "    try:\n",
    "        req = urllib.request.Request(f'{GCP_META}/{path}', headers={'Metadata-Flavor':'Google'})\n",
    "        return urllib.request.urlopen(req, timeout=3).read().decode().strip()\n",
    "    except: return None\n",
    "zone_full = gcp_meta('instance/zone')\n",
    "infra['gcp_zone']         = zone_full.split('/')[-1] if zone_full else None\n",
    "infra['gcp_machine_type'] = (gcp_meta('instance/machine-type') or '').split('/')[-1] or None\n",
    "infra['gcp_instance_id']  = gcp_meta('instance/id')\n",
    "try:\n",
    "    geo = _json.loads(urllib.request.urlopen('https://ipinfo.io/json', timeout=5).read())\n",
    "    infra.update({k: geo.get(k) for k in ['ip','city','region','country','timezone','loc','org']})\n",
    "except Exception as e: infra['geo_error'] = str(e)\n",
    "infra['hostname'] = socket.gethostname()\n",
    "print('='*50)\n",
    "for k,v in infra.items(): print(f'  {k:<22}: {v}')\n",
    "print('='*50)\n",
    "print('>>> Verify the OTHER session has a different IP/timezone before proceeding.')\n",
]))

# ── Cell 3 · JAX Engine ───────────────────────────────────────────────────────
cells.append(cc([
    "#@title 3 · JAX Engine (definitions only — run before Cells 4-6)\n",
    "try:\n",
    "    import jax, jax.numpy as jnp\n",
    "    from jax.experimental import io_callback\n",
    "    USE_JAX = True\n",
    "    n_devices = len(jax.devices())\n",
    "    print(f'JAX {jax.__version__}  backend={jax.default_backend()}  devices={n_devices}')\n",
    "except Exception as e:\n",
    "    USE_JAX = False\n",
    "    print(f'JAX unavailable: {e}  -- numpy fallback active')\n",
    "\n",
    "NATURAL_HZ    = None   # set by Cell 4\n",
    "BASE_MAT_SIZE = 256    # set by Cell 4\n",
    "_kern_cache   = {}\n",
    "_ts_lock      = threading.Lock()\n",
    "_ts_store     = {k: [] for k in range(N_STREAMS)}\n",
    "\n",
    "def _record_ts(k, t): \n",
    "    with _ts_lock: _ts_store[int(k)].append(float(t))\n",
    "\n",
    "if USE_JAX:\n",
    "    def make_kern(k, size):\n",
    "        @jax.jit\n",
    "        def _kern(key):\n",
    "            A = jax.random.normal(key, (size, size), dtype=jnp.float32)\n",
    "            B = jax.random.normal(jax.random.fold_in(key,1), (size, size), dtype=jnp.float32)\n",
    "            C = A @ B\n",
    "            t = io_callback(lambda: np.float32(time.perf_counter()), jax.ShapeDtypeStruct((), jnp.float32))\n",
    "            io_callback(lambda t: _record_ts(k, t), None, t)\n",
    "            return C.mean()\n",
    "        return _kern\n",
    "    def get_kern(k, size):\n",
    "        if (k,size) not in _kern_cache:\n",
    "            kern = make_kern(k, size)\n",
    "            kern(jax.random.PRNGKey(0))\n",
    "            _kern_cache[(k,size)] = kern\n",
    "        return _kern_cache[(k,size)]\n",
    "\n",
    "def make_shared_AB(size, shared_seed, lam, stream_profile, role):\n",
    "    \"\"\"Build A (shared ground state) and B (Alice adds Gaussian phase rotation).\"\"\"\n",
    "    rng = np.random.default_rng(int(shared_seed))\n",
    "    A   = rng.standard_normal((size, size)).astype(np.float32)\n",
    "    B   = rng.standard_normal((size, size)).astype(np.float32)\n",
    "    if role == 'Alice_Scramble' and lam > 0.01:\n",
    "        # Gaussian column-space rotation — changes EM signature, NOT dimensions\n",
    "        mu  = (size - 1) / 2.0\n",
    "        G   = np.exp(-0.5 * ((np.arange(size) - mu) / (SIGMA_GAUSSIAN * size / 4))**2).astype(np.float32)\n",
    "        G  /= G.max()\n",
    "        # Apply per-stream Gaussian weight\n",
    "        for k in range(N_STREAMS):\n",
    "            g_k = G * stream_profile[k] * lam\n",
    "            B  += g_k[:, None] * np.outer(G, B[int(mu), :])\n",
    "    return A, B\n",
    "\n",
    "def run_one_packet_timed(size, shared_seed, lam, stream_profile, packet_n, role):\n",
    "    \"\"\"Execute all 4 streams; return list of absolute timestamps.\"\"\"\n",
    "    A, B = make_shared_AB(size, shared_seed, lam, stream_profile, role)\n",
    "    t_abs = []\n",
    "    if USE_JAX:\n",
    "        for k in range(N_STREAMS):\n",
    "            kern = get_kern(k, size)\n",
    "            kern(jax.random.PRNGKey(packet_n * N_STREAMS + k))\n",
    "        jax.effects_barrier()\n",
    "        for k in range(N_STREAMS):\n",
    "            with _ts_lock:\n",
    "                t_abs.append(_ts_store[k].pop(0) if _ts_store[k] else 0.0)\n",
    "    else:\n",
    "        for k in range(N_STREAMS):\n",
    "            t1 = time.perf_counter()\n",
    "            _ = A @ B\n",
    "            t_abs.append(time.perf_counter())\n",
    "    return t_abs\n",
    "\n",
    "def principal_eigenvec(cov):\n",
    "    \"\"\"Largest-eigenvalue eigenvector of 4x4 cov — the dominant EM mode.\"\"\"\n",
    "    _, vecs = np.linalg.eigh(cov)\n",
    "    return vecs[:, -1]\n",
    "\n",
    "def eigvec_alignment(v1, v2):\n",
    "    \"\"\"Squared cosine similarity — 1=perfectly aligned, 0=orthogonal.\"\"\"\n",
    "    return float(np.dot(v1, v2)**2)\n",
    "\n",
    "def compute_lambda(elapsed):\n",
    "    phase = elapsed % CYCLE_S\n",
    "    if phase < RAMP_UP_S: return 0.5*(1-np.cos(np.pi*phase/RAMP_UP_S))\n",
    "    elif phase < RAMP_UP_S+ON_S: return 1.0\n",
    "    elif phase < RAMP_UP_S+ON_S+RAMP_DOWN_S:\n",
    "        p = (phase - RAMP_UP_S - ON_S)/RAMP_DOWN_S\n",
    "        return 0.5*(1+np.cos(np.pi*p))\n",
    "    return 0.0\n",
    "\n",
    "STREAM_MU      = (N_STREAMS-1)/2.0\n",
    "STREAM_PROFILE = np.array([np.exp(-0.5*((k-STREAM_MU)/SIGMA_GAUSSIAN)**2) for k in range(N_STREAMS)], dtype=np.float32)\n",
    "STREAM_PROFILE /= STREAM_PROFILE.max()\n",
    "print('Engine ready. Run Cell 4 next.')\n",
]))

# ── Cell 4 · Natural Frequency Discovery ─────────────────────────────────────
cells.append(cc([
    "#@title 4 · Natural Frequency Discovery (sweep tick rates ~7 min)\n",
    "# Finds the tick rate where eigenvalue entropy of cov is MINIMUM = most coherent EM state.\n",
    "# Both sessions should lock to the same rate for a shared coherent state.\n",
    "SWEEP_RATES = [0.5, 1.0, 2.0, 5.0, 10.0, 20.0]  # Hz\n",
    "SWEEP_PACKETS = 40  # packets per rate\n",
    "\n",
    "print('Sweeping tick rates to find natural TPU frequency...')\n",
    "print(f'  (warming up JIT first...)')\n",
    "# Warm up\n",
    "_ = run_one_packet_timed(128, 12345, 0.0, STREAM_PROFILE, 0, EXPERIMENT_ROLE)\n",
    "print(f'  JIT ready.')\n",
    "print()\n",
    "\n",
    "sweep_results = []\n",
    "for rate in SWEEP_RATES:\n",
    "    interval = 1.0 / rate\n",
    "    abs_ts = [[] for _ in range(N_STREAMS)]\n",
    "    t_loop_start = time.time()\n",
    "    for pn in range(SWEEP_PACKETS):\n",
    "        t_pkt = time.time()\n",
    "        row = run_one_packet_timed(128, 99999, 0.0, STREAM_PROFILE, pn, 'Bob_Passive')\n",
    "        for k in range(N_STREAMS): abs_ts[k].append(row[k])\n",
    "        # Pace to target rate\n",
    "        elapsed_pkt = time.time() - t_pkt\n",
    "        if elapsed_pkt < interval: time.sleep(interval - elapsed_pkt)\n",
    "    \n",
    "    # Compute diff timing + covariance\n",
    "    dts = np.array([np.diff(np.array(abs_ts[k]))*1000.0 for k in range(N_STREAMS)])\n",
    "    cov = np.cov(dts)\n",
    "    # Eigenvalue entropy\n",
    "    eigvals = np.linalg.eigvalsh(cov)\n",
    "    eigvals = eigvals[eigvals > 1e-12]\n",
    "    eigvals /= eigvals.sum()\n",
    "    H = float(-np.sum(eigvals * np.log(eigvals + 1e-12)))\n",
    "    actual_hz = SWEEP_PACKETS / (time.time() - t_loop_start)\n",
    "    sweep_results.append({'rate': rate, 'H': H, 'actual_hz': actual_hz, 'cov_trace': float(np.trace(cov))})\n",
    "    print(f'  {rate:5.1f} Hz (actual {actual_hz:5.1f} Hz): eigenvalue entropy H = {H:.4f}  Tr(Cov)={np.trace(cov):.2f}ms^2')\n",
    "\n",
    "best = min(sweep_results, key=lambda x: x['H'])\n",
    "NATURAL_HZ    = best['rate']\n",
    "NATURAL_INTERVAL = 1.0 / NATURAL_HZ\n",
    "BASE_MAT_SIZE = 256  # fixed — timing now paced by interval, not size\n",
    "print()\n",
    "print(f'>> NATURAL FREQUENCY: {NATURAL_HZ} Hz  (H={best[\"H\"]:.4f})  interval={NATURAL_INTERVAL*1000:.0f}ms')\n",
    "print(f'>> LOCK BOTH SESSIONS TO THIS RATE.')\n",
    "print(f'>> Tell the other operator: lock to {NATURAL_HZ} Hz')\n",
]))

# ── Cell 5 · Dry Run ──────────────────────────────────────────────────────────
cells.append(cc([
    "#@title 5 · Dry Run (60s, no injection) — establishes null alignment baseline\n",
    "# Measures eigenvector alignment between all 4 streams under no injection.\n",
    "# This is the null hypothesis: random noise alignment level.\n",
    "assert NATURAL_HZ is not None, 'Run Cell 4 first!'\n",
    "\n",
    "DRY_DURATION = 60.0\n",
    "print(f'60s dry run at {NATURAL_HZ} Hz (no injection, both roles same)...')\n",
    "\n",
    "null_alignments = []\n",
    "abs_buf = [[] for _ in range(N_STREAMS)]\n",
    "t0_dry = time.time()\n",
    "pn = 0\n",
    "while time.time() - t0_dry < DRY_DURATION:\n",
    "    t_pkt = time.time()\n",
    "    shared_seed = int(t_pkt // 10) * 10\n",
    "    row = run_one_packet_timed(BASE_MAT_SIZE, shared_seed, 0.0, STREAM_PROFILE, pn, 'Bob_Passive')\n",
    "    for k in range(N_STREAMS): abs_buf[k].append(row[k])\n",
    "    if len(abs_buf[0]) >= WINDOW_PACKETS + 1:\n",
    "        dts = np.array([np.diff(abs_buf[k][-(WINDOW_PACKETS+1):])*1000 for k in range(N_STREAMS)])\n",
    "        cov = np.cov(dts)\n",
    "        v   = principal_eigenvec(cov)\n",
    "        # Self-alignment (perfect = 1.0) — cross-stream check\n",
    "        null_alignments.append(eigvec_alignment(v, v))\n",
    "    elapsed = time.time() - t_pkt\n",
    "    if elapsed < NATURAL_INTERVAL: time.sleep(NATURAL_INTERVAL - elapsed)\n",
    "    pn += 1\n",
    "\n",
    "NULL_ALIGNMENT = float(np.mean(null_alignments)) if null_alignments else 0.5\n",
    "NULL_STD       = float(np.std(null_alignments))  if null_alignments else 0.1\n",
    "print(f'Null alignment baseline: {NULL_ALIGNMENT:.4f} +/- {NULL_STD:.4f}')\n",
    "print(f'Loop rate achieved: {pn/DRY_DURATION:.2f} Hz  (target={NATURAL_HZ})')\n",
    "go = pn/DRY_DURATION > NATURAL_HZ * 0.5\n",
    "print('>>> GO ✓' if go else '>>> WAIT ✗ — loop rate too low, try a lower NATURAL_HZ')\n",
]))

# ── Cell 6 · Main Capture ─────────────────────────────────────────────────────
cells.append(cc([
    "#@title 6 · Main Capture (15 min) + Download\n",
    "assert NATURAL_HZ is not None, 'Run Cells 4 and 5 first!'\n",
    "\n",
    "chunks_written = 0\n",
    "chunk_manifest = []\n",
    "abs_buf  = [[] for _ in range(N_STREAMS)]\n",
    "t0 = time.time()\n",
    "chunk_start = t0\n",
    "packet_n = 0\n",
    "\n",
    "print(f'[{EXPERIMENT_ROLE}] Starting at {time.strftime(\"%H:%M:%S UTC\", time.gmtime())}')\n",
    "print(f'Natural Hz: {NATURAL_HZ}  |  Expected chunks: {int(DURATION_SECONDS/CHUNK_SECONDS)}')\n",
    "print()\n",
    "\n",
    "while time.time() - t0 < DURATION_SECONDS:\n",
    "    t_pkt   = time.time()\n",
    "    elapsed = t_pkt - t0\n",
    "    lam     = compute_lambda(elapsed)\n",
    "    # Shared seed: both TPUs derive the same A,B from the same 10-second wall-clock bin\n",
    "    shared_seed = int(t_pkt // 10) * 10\n",
    "    \n",
    "    row = run_one_packet_timed(BASE_MAT_SIZE, shared_seed, lam, STREAM_PROFILE, packet_n, EXPERIMENT_ROLE)\n",
    "    for k in range(N_STREAMS): abs_buf[k].append(row[k])\n",
    "    \n",
    "    if time.time() - chunk_start >= CHUNK_SECONDS:\n",
    "        chunk_mid = (chunk_start + time.time()) / 2.0\n",
    "        min_len   = min(len(b) for b in abs_buf)\n",
    "        if min_len >= WINDOW_PACKETS + 1:\n",
    "            dts      = np.array([np.diff(abs_buf[k][-(WINDOW_PACKETS+1):])*1000 for k in range(N_STREAMS)])\n",
    "            cov      = np.cov(dts).astype(np.float32)\n",
    "            eigvals, eigvecs = np.linalg.eigh(cov)\n",
    "            princ_vec = eigvecs[:, -1].astype(np.float32)\n",
    "            eigvals_norm = eigvals / (eigvals.sum() + 1e-12)\n",
    "            eig_entropy = float(-np.sum(eigvals_norm * np.log(eigvals_norm + 1e-12)))\n",
    "            lam_mid   = float(compute_lambda(chunk_mid - t0))\n",
    "            \n",
    "            fname = f'chunk_{chunks_written:05d}.npz'\n",
    "            np.savez_compressed(\n",
    "                pathlib.Path(OUTPUT_DIR) / fname,\n",
    "                host_time_mid     = np.float64(chunk_mid),\n",
    "                stream_timing     = dts.astype(np.float32),\n",
    "                covariance_matrix = cov,\n",
    "                principal_eigvec  = princ_vec,\n",
    "                eigenvalues       = eigvals.astype(np.float32),\n",
    "                eigenvalue_entropy= np.float32(eig_entropy),\n",
    "                lambda_val        = np.float32(lam_mid),\n",
    "                shared_seed       = np.int64(int(chunk_mid // 10) * 10),\n",
    "                use_jax           = np.bool_(USE_JAX),\n",
    "                natural_hz        = np.float32(NATURAL_HZ),\n",
    "            )\n",
    "            chunk_manifest.append({'chunk': fname, 'host_time_mid': float(chunk_mid),\n",
    "                                   'lambda_val': lam_mid, 'eig_entropy': eig_entropy})\n",
    "            chunks_written += 1\n",
    "            for k in range(N_STREAMS): abs_buf[k] = abs_buf[k][-(WINDOW_PACKETS+1):]\n",
    "            chunk_start = time.time()\n",
    "            if chunks_written % 12 == 0:\n",
    "                phase = 'RAMP' if 0.01 < lam_mid < 0.99 else ('ON' if lam_mid >= 0.99 else 'OFF')\n",
    "                print(f'  [{elapsed:5.0f}s] chunk={chunks_written:3d}  lambda={lam_mid:.2f} ({phase})  H={eig_entropy:.3f}')\n",
    "    \n",
    "    dt_pkt = time.time() - t_pkt\n",
    "    if dt_pkt < NATURAL_INTERVAL: time.sleep(NATURAL_INTERVAL - dt_pkt)\n",
    "    packet_n += 1\n",
    "\n",
    "elapsed_total = time.time() - t0\n",
    "print(f'\\nCapture complete. {elapsed_total:.1f}s  |  Chunks: {chunks_written}  |  Packets: {packet_n}')\n",
    "print(f'Actual loop rate: {packet_n/elapsed_total:.2f} Hz')\n",
    "\n",
    "manifest = {\n",
    "    'schema_version': '4.0',\n",
    "    'dataset_type': 'shared_coherent_state_v4',\n",
    "    'role': EXPERIMENT_ROLE,\n",
    "    't0_utc': t0, 'duration_s': elapsed_total, 'n_chunks': chunks_written,\n",
    "    'n_streams': N_STREAMS, 'chunk_seconds': CHUNK_SECONDS,\n",
    "    'natural_hz': NATURAL_HZ, 'base_mat_size': BASE_MAT_SIZE,\n",
    "    'null_alignment': NULL_ALIGNMENT, 'null_alignment_std': NULL_STD,\n",
    "    'sigma_gaussian': SIGMA_GAUSSIAN, 'stream_profile': STREAM_PROFILE.tolist(),\n",
    "    'cycle_s': CYCLE_S, 'ramp_up_s': RAMP_UP_S, 'on_s': ON_S,\n",
    "    'ramp_down_s': RAMP_DOWN_S, 'off_s': OFF_S,\n",
    "    'infrastructure': infra,\n",
    "    'chunk_files': [c['chunk'] for c in chunk_manifest],\n",
    "    'chunks': chunk_manifest,\n",
    "}\n",
    "with open(f'{OUTPUT_DIR}/manifest.json','w') as f: json.dump(manifest, f, indent=2)\n",
    "\n",
    "archive = f'chronos_v4_{EXPERIMENT_ROLE.lower()}'\n",
    "shutil.make_archive(f'/tmp/{archive}', 'zip', OUTPUT_DIR)\n",
    "print(f'Archive: /tmp/{archive}.zip')\n",
    "try:\n",
    "    from google.colab import files\n",
    "    files.download(f'/tmp/{archive}.zip')\n",
    "except: print('Manual download: Files pane -> /tmp/')\n",
]))

cells.append(mc([
    "## After downloading both zips\n",
    "```powershell\n",
    "# Validate + full analysis\n",
    "python python/analyze_v4_experiment.py `\n",
    "    --alice 'mismo tiempo/holaMundo/chronos_v4_alice_scramble' `\n",
    "    --bob   'mismo tiempo/holaMundo/chronos_v4_bob_passive'\n",
    "```\n",
    "**Detection criteria:**\n",
    "- `pearson_r(lambda_alice, eigvec_alignment(t)) > 0, p < 0.05` → coherent state modulation\n",
    "- Peak of CCF(alignment, lambda) at `tau < 0` → retrocausal shadow\n",
    "- `eigenvalue_entropy` decreases during Alice ON → system becomes more ordered\n",
]))

nb = {
    "nbformat": 4, "nbformat_minor": 5,
    "metadata": {
        "accelerator": "TPU",
        "colab": {"name": "Chronos_Scramble_v4.ipynb", "provenance": []},
        "kernelspec": {"display_name": "Python 3", "name": "python3"},
        "language_info": {"name": "python"},
    },
    "cells": cells,
}
out = pathlib.Path("Chronos_Scramble_v4.ipynb")
out.write_text(json.dumps(nb, indent=1, ensure_ascii=False), encoding="utf-8")
print(f"Written: {out}  ({out.stat().st_size//1024} KB)  cells={len(cells)}")
